test(#1237): Resurrect `QnMergeTest`
yegor256/rultor pull request #1626
Opened 2023-03-04 10:06 UTC by volodya-lombrozo

1. Make `QnMergeTest` work
2. Add one more disabled test for #1237 (Verify CI checks before merge)

2023-03-05 09:05 UTC, volodya-lombrozo commented
Blocked by #1627

2023-03-10 09:02 UTC, volodya-lombrozo commented
@yegor256 Could you have a look, please?

2023-03-10 09:08 UTC, yegor256 requested changes
@volodya-lombrozo see a few comments

2023-03-10 09:08 UTC, yegor256 commented on src/main/java/com/rultor/agents/github/qtn/QnMerge.java
> +    public static final ResourceBundle PHRASES =
@volodya-lombrozo this is a bad idea

2023-03-10 09:08 UTC, yegor256 commented on src/main/resources/phrases_en_US.properties
> +QnMerge.checks-are-failed=Can't merge it, some checks were failed.
@volodya-lombrozo I would make a longer text here, with more details. Some people might be concerned about this situation and will think that the problem is in Rultor

2023-03-11 09:39 UTC, volodya-lombrozo commented
@yegor256 Reminder

2023-03-11 13:35 UTC, yegor256 commented
@rultor merge

2023-03-11 13:37 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/30611-1464913385)

2023-03-11 13:48 UTC, merged

2023-03-11 13:49 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/30611-1464913385) (took me 12min)